### ISSUE TITLE
Create Load Test for Solr that covers Reads and Writes

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/solr_load_testing#5]
Our goal for this ticket is to load test solr itself, not the application as a whole.  We'd like to know the thresholds (e.g. requests/second) at which performance starts to degrade.

Success criteria

- [x] Document how to do this, so that we can repeat it as needed. 
- [x] Write scenarios should mimic catalog indexing operations
- [x] Record the metrics as a benchmark.

This would be a good ticket to pair up on.

**Comment by sandbergja** [comment]
A few questions:

- Should this be a separate test plan from the existing Solr test plan?
- How does this sound for a test plan?
    - A sampler that POSTS several documents for solr to index, with [document IDs somehow derived from a random per-thread variable](https://www.perfmatrix.com/jmeter-random-variable/), so that each thread is writing documents with different IDs
    - A sampler that sends a commit
    - A sampler that deletes documents added in the first step, using the same random variable, so that threads don't delete each other's documents.

**Comment by maxkadel** [comment]
This strikes me as a good plan.

I have wondered about load testing deletes - I've wondered before if they have a bigger impact on performance than other actions.

Other things to think about - what should the documents look like? What should the config look like? (I'm assuming we should start with ones that look like the catalog right now).

Also, I think we should add Datadog on for staging before we run it, and find a good way to capture the data from there in a more permanent way.

I do notice that this plan doesn't seem to have updates to existing documents, which might be different from either new document writes or deletes.
